apiVersion: v1
kind: Service
metadata:
  name: {{ include "guestbook.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: guestbook
    tier: frontend
    {{- include "guestbook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  selector:
    app: guestbook
    tier: frontend